config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/mattiaBarbo/provaDocker1:
      branch: main
      repo: https://github.com/mattiaBarbo/provaDocker1
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/mattiaBarbo/provaDocker1 git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cardinal-mandrill.sh
        container: qc.acc_skanky-carmine-octopus
  QC.Doc:
    repos:
      github.com/mattiaBarbo/provaDocker1 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cinnamon-tang.sh
        container: qc.doc_gamy-grey-vulture
      github.com/mattiaBarbo/provaDocker1 git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-sapphire-elephant.sh
        container: qc.doc_flabby-plum-burmese
      github.com/mattiaBarbo/provaDocker1 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-khaki-bobcat.sh
        container: qc.doc_skanky-tangerine-coyote
  QC.Lic:
    repos:
      github.com/mattiaBarbo/provaDocker1 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-orange-ladybird.sh
        container: qc.lic_hilly-periwinkle-opossum
  QC.Sec:
    repos:
      github.com/mattiaBarbo/provaDocker1 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-azure-birman.sh
        container: qc.sec_craggy-orchid-rabbit
  QC.Sty:
    repos:
      github.com/mattiaBarbo/provaDocker1 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-silver-fousek.sh
        container: qc.sty_woolly-denim-rabbit
      github.com/mattiaBarbo/provaDocker1 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-chestnut-sloth.sh
        container: qc.sty_foggy-firebrick-camel
  QC.Uni:
    repos:
      github.com/mattiaBarbo/provaDocker1 commands:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-persimmon-wolfhound.sh
        container: qc.uni_hasty-salmon-oyster
  QC.Ver:
    repos:
      github.com/mattiaBarbo/provaDocker1 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-aqua-binturong.sh
        container: qc.ver_grumpy-yellow-argentino
timeout: 5400
